server:
  port: 8080

spring:
  application:
    name: demo1
  datasource:
    url: jdbc:mysql://192.168.31.42:3306/databaseV1?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 200 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: KitariPool # 连接池名称
      # redis
  data:
    redis:
      host: 192.168.31.42
      port: 6379
      database: 0
  cache:
    redis:
      time-to-live: 3000s
      key-prefix: "cache:"
      use-key-prefix: true
      cache-null-values: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

springdoc:
  default-flat-param-object: true

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    prometheus:
      access: unrestricted

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: isDeleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0