spring:
  application:
    name: demo1
  datasource:
    url: jdbc:mysql://192.168.31.98:3306/databaseV1?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



#global logic delete

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: isDeleted
#      logic-delete-value: 1
#      logic-not-delete-value: 0